const action_type = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  RANDOM_PRODUCT: "RANDOM_PRODUCT",
  CATEGORY_PRODUCTS: "CATEGORY_PRODUCTS",
  SET_CATEGORIES: "SET_CATEGORIES",
};

export { action_type };
